---
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install nginx
      yum: 
        name: nginx
        state: present
    - name: start nginx 
      service:
        name: nginx
        state: started
    - name: Update nginx config
      template: src=../templates/config_files/nginx.conf
        dest=/etc/nginx/nginx.conf
        backup=yes
    - name: Update index page
      template: src=../templates/static/index.html
        dest=/usr/share/nginx/html/index.html
        backup=yes
    - name: restart haproxy
      service:
        name: nginx 
        state: restarted
    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: restarted
