---
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install python3
      yum:
        name:
          - python-setuptools
          - python36
          - python36-pip
          - python36-devel
        state: present

# Application install
- hosts: appServer
  become: yes
  become_user: vagrant
  tasks:
    - name: Create app_simple directory
      file:
        path: /home/vagrant/app_simple
        state: directory
        owner: vagrant
        group: vagrant
        mode: u=rwx,g=rx,o=rx
    - name: Copy application files into app_simple directory
      copy: 
        src: ../templates/app_simple/ 
        dest: /home/vagrant/app_simple/ 
        remote_src: no
        directory_mode: yes
        owner: vagrant
        group: vagrant
        mode: u=rwx,g=rx,o=rx
    - name: Install app_simple requirements
      pip: 
        requirements: /home/vagrant/app_simple/requirements.txt
        executable: pip3
        extra_args: --user

    # needs rsync
    # - synchronize: 
    #     src: ../templates/app_simple
    #     dest: /home/vagrant/

# Systemd configuration
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Copy systemd configuration
      copy: 
        src: ../templates/config_files/app_simple.service
        dest: /etc/systemd/system/app_simple.service
        remote_src: no
    - name: start app_simple
      service:
        name: app_simple
        state: started

# Nginx integration
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create nginx directories
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      with_items:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled
    - name: Copy nginx site configuration
      copy: 
        src: ../templates/config_files/app_simple.com.conf
        dest: /etc/nginx/sites-available/app_simple.com.conf
        remote_src: no
    - name: Create site symbolic link 
      file:
        src: /etc/nginx/sites-available/app_simple.com.conf
        dest:  /etc/nginx/sites-enabled/app_simple.com.conf
        state: link
    - name: validate configuration
      command: nginx -t
    - name: restart nginx
      service:
        name: nginx 
        state: restarted
    - name: Insert entry to hosts file for testing
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 app_simple.com